---
- hosts: localhost
  tasks:
    - name: crer usuario
      user:
        name: "{{name}}"
        shell: /bin/bash
        uid: "{{uid}}"
        password: "{{ password | password_hash('sha512') }}"
