---
- hosts: localhost
  vars:
    password: "1234"
  tasks:
    - name: crer usuario
      user:
        name: "{{name}}"
        shell: /bin/bash
        uid: 1010
        password: "{{ password | password_hash('sha512') }}"
